import {useEffect,useMemo,useState} from 'react';
import {CalendarDays,CheckCircle2,MessageSquare,Plus,RefreshCw,Search,Users} from 'lucide-react';
import type {SellableTourDeparture} from '../types';
import {addSalesTourNote,loadSellableTourDepartures} from '../lib/tourDepartures';
import './TourSalesBoard.css';

export default function TourSalesBoard({onAddReservation}:{onAddReservation:(departure:SellableTourDeparture)=>void}){
  const [from,setFrom]=useState(offsetDate(-14));const [to,setTo]=useState(offsetDate(120));const [rows,setRows]=useState<SellableTourDeparture[]>([]);
  const [query,setQuery]=useState('');const [status,setStatus]=useState('Todos');const [loading,setLoading]=useState(true);const [message,setMessage]=useState('');const [drafts,setDrafts]=useState<Record<string,string>>({});const [saving,setSaving]=useState('');
  const load=async()=>{setLoading(true);setMessage('');try{setRows(await loadSellableTourDepartures(from,to))}catch(error:any){setMessage(error?.message||'No se pudieron cargar los tours.')}finally{setLoading(false)}};
  useEffect(()=>{void load()},[from,to]);
  const filtered=useMemo(()=>rows.filter(row=>{if(status!=='Todos'&&row.status!==status)return false;const q=query.trim().toLowerCase();return !q||[row.departure_code,row.product_name,row.tour_id,row.modality,row.notes,row.latest_sales_note].join(' ').toLowerCase().includes(q)}),[rows,query,status]);
  const addNote=async(row:SellableTourDeparture)=>{setSaving(row.departure_id);setMessage('');try{await addSalesTourNote(row.departure_id,drafts[row.departure_id]||'');setDrafts(current=>({...current,[row.departure_id]:''}));await load()}catch(error:any){setMessage(error?.message||'No se pudo guardar la nota.')}finally{setSaving('')}};
  const metrics={tours:rows.length,open:rows.filter(row=>row.status==='open').length,reservations:rows.reduce((sum,row)=>sum+Number(row.reservation_count||0),0),pax:rows.reduce((sum,row)=>sum+Number(row.confirmed_pax||0),0)};
  return <section className="tour-sales-board"><header><div><span>HOTEL EXPERIENCE · VISTA DE VENTAS</span><h1>Tours asignados y procesos completados</h1><p>Misma salida operacional, en modo comercial: puedes sumar una reserva a un tour disponible y dejar notas para Operaciones.</p></div><div className="tour-sales-metrics"><Metric value={metrics.tours} label="Tours"/><Metric value={metrics.open} label="Abiertos"/><Metric value={metrics.reservations} label="Reservas"/><Metric value={metrics.pax} label="Pax"/></div></header>
    <div className="tour-sales-toolbar"><label><span>Desde</span><input type="date" value={from} onChange={event=>setFrom(event.target.value)}/></label><label><span>Hasta</span><input type="date" value={to} onChange={event=>setTo(event.target.value)}/></label><div className="tour-sales-search"><Search size={15}/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Buscar código tour, producto, modalidad o nota…"/></div><select value={status} onChange={event=>setStatus(event.target.value)}><option>Todos</option><option value="open">Abiertos</option><option value="closed">Cerrados</option><option value="completed">Completados</option><option value="cancelled">Cancelados</option></select><button onClick={()=>void load()}><RefreshCw size={14}/> Actualizar</button></div>
    {message&&<div className="tour-sales-message">{message}</div>}
    {loading?<div className="tour-sales-empty">Cargando tours…</div>:<div className="tour-sales-table-wrap"><table><thead><tr><th>Código tour</th><th>Fecha / hora</th><th>Producto / tipo</th><th>Pax / cupo</th><th>Reservas</th><th>Estado</th><th>Nota para Operaciones</th><th>Acción comercial</th></tr></thead><tbody>{filtered.map(row=>{const canSell=row.status==='open'&&row.modality!=='privado'&&(row.available_pax==null||row.available_pax>0);return <tr key={row.departure_id}><td><b className="tour-code">{row.departure_code}</b><small>{row.tour_id}</small></td><td><b>{dateLabel(row.service_date)}</b><small>{time(row.start_time)}</small></td><td><b>{row.product_name}</b><span className={`tour-sales-tag ${row.modality}`}>{modality(row.modality)}</span></td><td><div className="tour-sales-pax"><Users size={14}/><b>{row.confirmed_pax}/{row.capacity_total||'—'}</b></div><small>{row.available_pax==null?'Cupo sin definir':`${row.available_pax} disponible(s)`}</small></td><td><b>{row.reservation_count}</b><small>reservas enlazadas</small></td><td><Status value={row.status}/></td><td><div className="tour-note-input"><input value={drafts[row.departure_id]||''} onChange={event=>setDrafts(current=>({...current,[row.departure_id]:event.target.value}))} placeholder="Nota visible por Operaciones"/><button disabled={saving===row.departure_id||!(drafts[row.departure_id]||'').trim()} onClick={()=>void addNote(row)}><MessageSquare size={13}/></button></div><small>{row.latest_sales_note||row.notes||'Sin notas'}</small></td><td>{canSell?<button className="tour-add-reservation" onClick={()=>onAddReservation(row)}><Plus size={14}/> Sumar reserva</button>:<small>{row.modality==='privado'?'Tour privado':row.status!=='open'?'No admite venta':'Sin cupos'}</small>}</td></tr>})}</tbody></table>{!filtered.length&&<div className="tour-sales-empty"><CalendarDays size={22}/><b>No hay tours en este rango o filtro.</b></div>}</div>}
  </section>;
}

function Metric({value,label}:{value:number;label:string}){return <div><b>{value}</b><span>{label}</span></div>}
function Status({value}:{value:string}){return <span className={`tour-sales-status ${value}`}>{value==='completed'?<CheckCircle2 size={12}/>:null}{value==='open'?'Abierto':value==='completed'?'Completado':value==='closed'?'Cerrado':'Cancelado'}</span>}
function modality(value:string){return value==='semiprivado'?'Semiprivado':value==='privado'?'Privado':'Regular'}
function time(value?:string|null){return value?String(value).slice(0,5):'Hora por definir'}
function dateLabel(value:string){const [y,m,d]=value.split('-').map(Number);return new Intl.DateTimeFormat('es-CL',{weekday:'short',day:'2-digit',month:'short',year:'numeric'}).format(new Date(y,m-1,d,12))}
function offsetDate(days:number){const date=new Date();date.setUTCDate(date.getUTCDate()+days);return date.toISOString().slice(0,10)}
